/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tela;

import apoio.Formatacao;
import apoio.Validacao;
import dao.MovestoqueDAO;
import dao.ProdutoDAO;
import dao.RelatoriosDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Back
 */
public class IfrRelatorioMovimentacao extends javax.swing.JInternalFrame {

    /** Creates new form IfrConsultaEstoque */
    public IfrRelatorioMovimentacao() {
        initComponents();
        ProdutoDAO prodDAO = new ProdutoDAO();
        Formatacao.formatarData(tfdFdataIniciall);
        Formatacao.formatarHora(tfdFHoraInicial);
        Formatacao.formatarHora(tfdFHoraFinal);
        Formatacao.formatarData(tfdFdataFinal);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfdFdataIniciall = new javax.swing.JFormattedTextField();
        tfdFdataFinal = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfdFHoraInicial = new javax.swing.JFormattedTextField();
        tfdFHoraFinal = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxOper = new javax.swing.JComboBox<>();
        BtnCarregarInfo = new javax.swing.JButton();
        btnPesquisarProd3 = new javax.swing.JButton();

        tfdFdataIniciall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdFdataIniciallActionPerformed(evt);
            }
        });

        tfdFdataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdFdataFinalActionPerformed(evt);
            }
        });

        jLabel1.setText("Data Inicial");

        jLabel2.setText("Data Final");

        jLabel3.setText("Hora Inicial");

        jLabel4.setText("Hora Final");

        tfdFHoraInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tfdFHoraInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdFHoraInicialActionPerformed(evt);
            }
        });

        tfdFHoraFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tfdFHoraFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdFHoraFinalActionPerformed(evt);
            }
        });

        jLabel6.setText("Operação");

        jComboBoxOper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Entrada", "Saída" }));

        BtnCarregarInfo.setText("Gerar");
        BtnCarregarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarregarInfoActionPerformed(evt);
            }
        });

        btnPesquisarProd3.setText("Fechar");
        btnPesquisarProd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProd3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnCarregarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPesquisarProd3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfdFdataIniciall, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdFdataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfdFHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfdFHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdFdataIniciall, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(tfdFHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(tfdFdataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfdFHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addComponent(BtnCarregarInfo)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisarProd3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdFdataIniciallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdFdataIniciallActionPerformed

    }//GEN-LAST:event_tfdFdataIniciallActionPerformed

    private void tfdFdataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdFdataFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdFdataFinalActionPerformed

    private void tfdFHoraInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdFHoraInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdFHoraInicialActionPerformed

    private void tfdFHoraFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdFHoraFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdFHoraFinalActionPerformed

    private void BtnCarregarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarregarInfoActionPerformed
           Validacao valida = new Validacao();
            RelatoriosDAO rdao = new RelatoriosDAO();
            String dataini = tfdFdataIniciall.getText();
            String datafi = tfdFdataFinal.getText();
            String horaini = tfdFHoraInicial.getText();
            String horafi = tfdFHoraFinal.getText();
            int codoper = jComboBoxOper.getSelectedIndex();
            String periodoinicial = "'" + dataini + " " + horaini + "'";
            String periodofinal = "'" + datafi + " " + horafi + "'";
            String operacao = "";
            if (codoper == 1) {
                operacao = "'E'";
            }
            if (codoper == 2) {
                operacao = "'S'";
            }
           
                    
        if ((valida.validarDataFormatada(tfdFdataIniciall.getText()) == false) || (valida.validarDataFormatada(tfdFdataFinal.getText()) == false)) {
             JOptionPane.showMessageDialog(null, "A data preenchida é inválida");
         } else { 
         if ((valida.validaHora(tfdFHoraInicial.getText()) == false) || (valida.validaHora(tfdFHoraFinal.getText()) == false))  {
             JOptionPane.showMessageDialog(null, "A hora preenchida é inválida");  
         } else {
                if (jComboBoxOper.getSelectedIndex() == 0) {
               JOptionPane.showMessageDialog(null, "Por favor selecione uma operação");  
             } else {
                    
                }
         }
        }
         rdao.geraRelatorioMovEstoque(periodoinicial, periodofinal, operacao);
    }//GEN-LAST:event_BtnCarregarInfoActionPerformed

    private void btnPesquisarProd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProd3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnPesquisarProd3ActionPerformed

 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCarregarInfo;
    private javax.swing.JButton btnPesquisarProd3;
    private javax.swing.JComboBox<String> jComboBoxOper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JFormattedTextField tfdFHoraFinal;
    private javax.swing.JFormattedTextField tfdFHoraInicial;
    private javax.swing.JFormattedTextField tfdFdataFinal;
    private javax.swing.JFormattedTextField tfdFdataIniciall;
    // End of variables declaration//GEN-END:variables

}
